---
 - hosts: local
   connection: local
   gather_facts: no
   vars_files:
     - aws/vars/vpc.yml
     - aws/vars/ec2_key.yml
   tasks:
     - import_tasks: aws/tasks/vpc.yml
     - import_tasks: aws/tasks/ec2_key.yml


