---
 - name: VPC | Creating an AWS VPC inside mentioned Region
   local_action:
     module: ec2_vpc_net
     region: "{{ vpc_region }}"
     state: present
     cidr_block: "{{ vpc_cidr_block }}"
     resource_tags: { "Name":"{{ vpc_name }}-vpc" }
     name: "{{ vpc_name }}-vpc"
   register: vpc

 - name: VCP | debug info 
   debug: 
     var: vpc.vpc

 - name: VPC | Create gateway
   ec2_vpc_igw:
    vpc_id: "{{ vpc.vpc.id }}"
    state: present
    region: "{{ vpc_region }}"
   register: igw

 - name: VCP | debug info
   debug:
     var: "vpc_subnets"


 - name: VPC | Create public Subnet 1
   ec2_vpc_subnet:
     state: present
     vpc_id: "{{ vpc.vpc.id }}"
     az: "{{ vpc_subnets[0].az }}"
     cidr: "{{ vpc_subnets[0].cidr }}"
     resource_tags: "{{ vpc_subnets[0].resource_tags }}"
     region: "{{ vpc_region }}"
   register: public_subnet_1

 - name: VCP | debug info
   debug:
     var: "public_subnet_1"

 - name: VPC | Create public Subnet 2
   ec2_vpc_subnet:
     state: present
     vpc_id: "{{ vpc.vpc.id }}"
     az: "{{ vpc_subnets[1].az }}"
     cidr: "{{ vpc_subnets[1].cidr }}"
     resource_tags: "{{ vpc_subnets[1].resource_tags }}"
     region: "{{ vpc_region }}"
   register: public_subnet_2

 - name: VPC | Create private subnet 1 
   ec2_vpc_subnet:
     state: present
     vpc_id: "{{ vpc.vpc.id }}"
     az: "{{ vpc_subnets[2].az }}"
     cidr: "{{ vpc_subnets[2].cidr }}"
     resource_tags: "{{ vpc_subnets[2].resource_tags }}"
     region: "{{ vpc_region }}"
   register: private_subnet_1

 - name: VCP | debug info
   debug:
     var: "private_subnet_1"


 - name: VPC | Create private subnet 2
   ec2_vpc_subnet:
     state: present
     vpc_id: "{{ vpc.vpc.id }}"
     az: "{{ vpc_subnets[3].az }}"
     cidr: "{{ vpc_subnets[3].cidr }}"
     resource_tags: "{{ vpc_subnets[3].resource_tags }}"
     region: "{{ vpc_region }}"
   register: private_subnet_2

 - name: VCP | debug info
   debug:
     var: "private_subnet_2"


 - name: VPC | Set up public subnet route table
   ec2_vpc_route_table:
     vpc_id: "{{ vpc.vpc.id }}"
     region: "{{ vpc_region }}"
     tags:
       Name: Public
     subnets:
       - "{{ public_subnet_1.subnet.id  }}"
       - "{{ public_subnet_2.subnet.id  }}"
     routes:
       - dest: 0.0.0.0/0
         gateway_id: "{{ igw.gateway_id }}"
   register: public_route_table
 

 - name: VPC | Write vpc id to file inside the vars directory
   shell: echo "{{ vpc.vpc.id }}" > "{{ vpc_name }}-vpc-info.yml"
   args:
     chdir: aws/vars/

 - name: VPC | Write public and private subnets id to files inside the vars directory
   shell: echo "{{ public_subnet_1.subnet.id }}" > "{{ public_subnet_1.subnet.tags.Name }}.yml"
   args:
     chdir: aws/vars/
   with_items: "{{ public_subnet_1 }}"


 - name: VPC | Write public and private subnets id to files inside the vars directory
   shell: echo "{{ public_subnet_2.subnet.id }}" > "{{ public_subnet_2.subnet.tags.Name }}.yml"
   args:
     chdir: aws/vars/
   with_items: "{{ public_subnet_2 }}"


 - name: VPC | Write public and private subnets id to files inside the vars directory
   shell: echo "{{ private_subnet_1.subnet.id }}" > "{{ private_subnet_1.subnet.tags.Name }}.yml"
   args:
     chdir: aws/vars/
   with_items: "{{ private_subnet_1 }}"

 - name: VPC | Write public and private subnets id to files inside the vars directory
   shell: echo "{{ private_subnet_2.subnet.id }}" > "{{ private_subnet_2.subnet.tags.Name }}.yml"
   args:
     chdir: aws/vars/
   with_items: "{{ private_subnet_2 }}"


 - name: VPC | Set the public and private subnet id as facts
   set_fact:
     vpc_id: "{{ lookup('file', 'aws/vars/' + vpc_name + '-vpc-info.yml') }}"
     public_subnet_1: "{{ lookup('file', 'aws/vars/' + vpc_name + '-' + public_az_1 + '-public-subnet.yml') }}"
     public_subnet_2: "{{ lookup('file', 'aws/vars/' + vpc_name + '-' + public_az_2 + '-public-subnet.yml') }}"
     private_subnet_1: "{{ lookup('file', 'aws/vars/' + vpc_name + '-' + private_az_1 + '-private-subnet.yml') }}"
     private_subnet_2: "{{ lookup('file', 'aws/vars/' + vpc_name + '-' + private_az_2 + '-private-subnet.yml') }}"


